name: Build and deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      - name: Install and build 🔧
        run: | # Install packages and build the static files
          mkdir docs-build || true
          cd wolves_app
          yarn
          CI=false yarn build
          cd ..
          cp -r wolves_app/build/* docs-build/
          cp -r build/* docs-build/
      - name: copy catalogue metadata
        run: |
          cp mc_meta.json docs-build/mc_meta.json
          cp -r assets docs-build/assets
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: main # branch the action should deploy to.
          FOLDER: docs-build # folder containing the build
          CLEAN: true # Automatically remove deleted files from the deploy branch
          TARGET_FOLDER: docs # The folder that we serve our Storybook files from
